version: '3'
services:
  api:
    container_name: flask-container
    build:
      context: .
      dockerfile: Dockerfile 
    entrypoint: python app.py
    env_file:
      - flask_cache/.env
    ports:
      - '5000:5000'
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"